from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors

from app.analytics.recommendations.ml_recommendations import (
    generate_ml_recommendations
)


def generate_pdf_report(data, path):

    doc = SimpleDocTemplate(path)

    styles = getSampleStyleSheet()

    elements = []

    # =========================
    # HEADER
    # =========================

    elements.append(
        Paragraph(
            "ACCURATE INDUSTRIES",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            "Industrial Intelligence & Manufacturing Analytics Suite",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 25))

    # =========================
    # EXECUTIVE SUMMARY
    # =========================

    elements.append(
        Paragraph(
            "Executive Summary",
            styles["Heading1"]
        )
    )

    dashboard = data["dashboard"]
    kpis = data["kpis"]

    summary = [

        f"Total Inquiries: {dashboard['total_inquiries']}",
        f"Completion Rate: {dashboard['completion_rate']}%",
        f"Repeat Customers: {dashboard['repeat_customers']}",
        f"Average Products per Inquiry: {dashboard['average_products_per_inquiry']}",
        f"Top Product: {kpis['top_product']}",
        f"Top Customer: {kpis['top_customer']}"

    ]

    for item in summary:

        elements.append(
            Paragraph(
                f"• {item}",
                styles["Normal"]
            )
        )

    elements.append(Spacer(1, 25))

    # =========================
    # TOP PRODUCTS
    # =========================

    elements.append(
        Paragraph(
            "Top Product Demand",
            styles["Heading1"]
        )
    )

    product_table = [["Product", "Requests"]]

    for product in data["products"][:10]:

        product_table.append([
            product["product"],
            str(product["requests"])
        ])

    table = Table(product_table)

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey)

        ])

    )

    elements.append(table)

    elements.append(Spacer(1, 25))

    # =========================
    # TOP CUSTOMERS
    # =========================

    elements.append(
        Paragraph(
            "Key Customers",
            styles["Heading1"]
        )
    )

    customer_table = [["Customer", "Inquiries"]]

    for customer in data["customers"][:10]:

        customer_table.append([
            customer["customer"],
            str(customer["total_inquiries"])
        ])

    table = Table(customer_table)

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey)

        ])

    )

    elements.append(table)

    elements.append(Spacer(1, 25))

    # =========================
    # AI RECOMMENDATIONS
    # =========================

    elements.append(
        Paragraph(
            "AI Production Recommendations",
            styles["Heading1"]
        )
    )

    recommendations = generate_ml_recommendations(
        data["forecast"]
    )

    for item in recommendations[:10]:

        elements.append(

            Paragraph(

                f"• {item['product']} → "
                f"{item['recommendation']} "
                f"(Predicted Demand: {item['prediction']})",

                styles["Normal"]

            )

        )

    elements.append(Spacer(1, 30))

    # =========================
    # FOOTER
    # =========================

    elements.append(

        Paragraph(

            "Generated by Accurate AI Analytics Engine<br/>"
            "Powered by Machine Learning, Predictive Analytics and Business Intelligence.",

            styles["Normal"]

        )

    )

    doc.build(elements)